package protopost.server.exception

class ProtopostException( message : String, cause : Throwable = null ) extends Exception( message, cause )

final class ApparentBug( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadIdentifierFormat( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadCookieSettings( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadCredentials( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadLocation( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadMedia( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadMediaPath( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadPostDefinition( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadSeismicNodeId( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadService( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadServiceUrl( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class BadSubject( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class EmailIsAlreadyRegistered( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class InconsistentSeismicNodeDefinition( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class InsecureConfigurationPropertiesFile( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class InsufficientPermissions( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class MissingConfig( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class NotLoggedIn( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class ResourceNotFound( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class SignatureDoesNotVerify( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class UnacceptableContentType( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class UnknownAlgorithmOrCurve( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class UnknownDestination( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class UnknownPost( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class UnknownPoster( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class UnknownSeismicNode( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
final class UnsupportedProtocol( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
//final class InvalidJwt( message : String, cause : Throwable = null ) extends ProtopostException( message, cause )
